# Generated by Django 4.2.15 on 2024-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do material"),
                ),
                (
                    "unidade_medida",
                    models.CharField(max_length=15, verbose_name="Unidade de medida"),
                ),
            ],
            options={"verbose_name_plural": "Materiais",},
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Codigo do serviço"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do serviço"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "unidade_medida",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Unidade de medida"
                    ),
                ),
                (
                    "quantidade",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Quantidade"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Serviços",},
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do projeto"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("dt_criacao", models.DateField(verbose_name="Data de criação")),
                (
                    "lista_de_materiais",
                    models.ManyToManyField(
                        to="app_gerenciador.material", verbose_name="Lista de materiais"
                    ),
                ),
                (
                    "lista_de_servicos",
                    models.ManyToManyField(
                        to="app_gerenciador.servico",
                        verbose_name="Lista de codigo de serviços",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Projetos",},
        ),
    ]
